version: "3"
services:
  mysql:
    container_name: mysql
    ports:
    - '3307:3306'
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: prisma
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
        - mysql:/var/lib/mysql
  prisma:
    image: prismagraphql/prisma
    restart: always
    links:
      - mysql
    depends_on: 
      - mysql
    container_name: prisma
    ports:
      - '5555:5555'
    environment: 
      PRISMA_CONFIG: |
        port: 5555
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: prisma
            password: ${MYSQL_PASSWORD}
    build:
      context: app/prisma
      dockerfile: Dockerfile
    volumes:
      - /app/prisma
  frontend:
    links:
      - mysql
    depends_on: 
      - mysql
  frontend:
    container_name: app
    ports:
      - '3000:3000'
    build:
      context: app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - /app/node_modules
      - /app/.next
volumes: 
    mysql: