import 'tailwindcss/tailwind.css'
// import { GetStaticProps } from "next";
// import superjson from 'superjson';
// import { PrismaClient } from '@prisma/client'
import Head from 'next/head'
import React from 'react'


// const Accounts = (props) => {
//   return (
//       <div class="overflow-x-auto">
//       <table class="table w-full table-zebra">
        
//         <thead>
//           <tr>
//             <th></th> 
//             <th>Name</th> 
//             <th>Create Date</th> 
//             <th>Update Date</th>
//           </tr>
//         </thead> 
//         {props.allAccounts.map((account) => (
//         <tbody>
//           <tr key={account.id}>
//             <th>9</th> 
//             <td>account.name</td> 
//             <td>account.create_date</td> 
//             <td>account.update_date</td>
//           </tr>
//         </tbody>
//         ))}
//       </table>
//       </div>
//     )
//   } 

export default function Home ():any {
  return (
  
    <div className="grid-rows-4" data-theme="cupcake">
      <Head>
        <title>Document Management</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className="navbar mb-2 shadow-lg bg-neutral text-neutral-content rounded-box">
          <div className="flex-1 px-2 mx-2">
            <span className="text-lg font-bold">
                    DaisyUI
            </span>
          </div>
         
          <div className="flex-none hidden px-2 mx-2 lg:flex">
            <div className="flex items-stretch">
              <a className="btn btn-ghost btn-sm rounded-btn">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" className="inline-block w-5 mr-2 stroke-current">              
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"></path>            
                </svg>
                      Likes
                    
              </a> 
              <a className="btn btn-ghost btn-sm rounded-btn">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" className="inline-block w-5 mr-2 stroke-current">     
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9"></path>                     
                </svg>
                      Notifications
                    
              </a> 
              <a className="btn btn-ghost btn-sm rounded-btn">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" className="inline-block w-5 mr-2 stroke-current">          
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 7v10a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-6l-2-2H5a2 2 0 00-2 2z"></path>                
                </svg>
                      Files
                    
              </a> 
              <a className="btn btn-ghost btn-sm rounded-btn">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" className="inline-block w-5 mr-2 stroke-current">       
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4"></path>                   
                </svg>
                      Config
                    
              </a>
            </div>
          </div> 
          <div className="flex-none">
            <button className="btn btn-square btn-ghost">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" className="inline-block w-6 h-6 stroke-current">           
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>               
              </svg>
            </button>
          </div>
        </div>
      
  

        <div className="overflow-x-auto">
        <table className="table w-full table-zebra">
          <thead>
            <tr>
              <th></th> 
              <th>Name</th> 
              <th>Job</th> 
              <th>Favorite Color</th>
            </tr>
          </thead> 
          <tbody>
            <tr>
              <th>9</th> 
              <td>Lesya Tinham</td> 
              <td>Safety Technician IV</td> 
              <td>Maroon</td>
            </tr>
            <tr>
              <th>10</th> 
              <td>Zaneta Tewkesbury</td> 
              <td>VP Marketing</td> 
              <td>Green</td>
            </tr>
            <tr>
              <th>11</th> 
              <td>Andy Tipple</td> 
              <td>Librarian</td> 
              <td>Indigo</td>
            </tr>
            <tr>
              <th>12</th> 
              <td>Sophi Biles</td> 
              <td>Recruiting Manager</td> 
              <td>Maroon</td>
            </tr>
          </tbody>
        </table>
      </div>
        


      <div className="md:container md:mx-auto">
        <button className="btn">neutral</button> 
        <button className="btn btn-primary">primary</button> 
        <button className="btn btn-secondary">secondary</button> 
        <button className="btn btn-accent">accent</button> 
        <button className="btn btn-ghost">ghost</button> 
        <button className="btn btn-link">link</button>

      </div>
  
      <footer className="items-center p-4 footer bg-neutral text-neutral-content">
          <div className="flex items-center">
            <svg width="24" height="24" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" fill-rule="evenodd" clip-rule="evenodd" className="fill-current">
              <path d="M22.672 15.226l-2.432.811.841 2.515c.33 1.019-.209 2.127-1.23 2.456-1.15.325-2.148-.321-2.463-1.226l-.84-2.518-5.013 1.677.84 2.517c.391 1.203-.434 2.542-1.831 2.542-.88 0-1.601-.564-1.86-1.314l-.842-2.516-2.431.809c-1.135.328-2.145-.317-2.463-1.229-.329-1.018.211-2.127 1.231-2.456l2.432-.809-1.621-4.823-2.432.808c-1.355.384-2.558-.59-2.558-1.839 0-.817.509-1.582 1.327-1.846l2.433-.809-.842-2.515c-.33-1.02.211-2.129 1.232-2.458 1.02-.329 2.13.209 2.461 1.229l.842 2.515 5.011-1.677-.839-2.517c-.403-1.238.484-2.553 1.843-2.553.819 0 1.585.509 1.85 1.326l.841 2.517 2.431-.81c1.02-.33 2.131.211 2.461 1.229.332 1.018-.21 2.126-1.23 2.456l-2.433.809 1.622 4.823 2.433-.809c1.242-.401 2.557.484 2.557 1.838 0 .819-.51 1.583-1.328 1.847m-8.992-6.428l-5.01 1.675 1.619 4.828 5.011-1.674-1.62-4.829z"></path>
            </svg> 
            <p>Copyright © 2021 - All right reserved</p>
          </div> 
          <div className="grid-flow-col gap-4 md:place-self-center md:justify-self-end">
            <a>
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" className="fill-current">
                <path d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"></path>
              </svg>
            </a> 
            <a>
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" className="fill-current">
                <path d="M19.615 3.184c-3.604-.246-11.631-.245-15.23 0-3.897.266-4.356 2.62-4.385 8.816.029 6.185.484 8.549 4.385 8.816 3.6.245 11.626.246 15.23 0 3.897-.266 4.356-2.62 4.385-8.816-.029-6.185-.484-8.549-4.385-8.816zm-10.615 12.816v-8l8 3.993-8 4.007z"></path>
              </svg>
            </a> 
            <a>
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" className="fill-current">
                <path d="M9 8h-3v4h3v12h5v-12h3.642l.358-4h-4v-1.667c0-.955.192-1.333 1.115-1.333h2.885v-5h-3.808c-3.596 0-5.192 1.583-5.192 4.615v3.385z"></path>
              </svg>
            </a>
          </div>
       </footer>


    </div>
  )
}

// const prisma = new PrismaClient();

// export const getStaticProps = async () => {
//   const allAccounts = await prisma.accounts.findMany()
//   if(allAccounts){
//     return {
//       props: {
//         allAccounts
//       }
//     }
//   }else{
//     <div>"loading..."</div>
//   }
 
// }

// export default Accounts;