import 'tailwindcss/tailwind.css'
import Head from 'next/head'
import React from 'react'

const Header = () =>{
    return(
        <div className="flex flex-row" data-theme="cupcake">
        <Head>
          <title>Document Management</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
          <div className="navbar mb-2 shadow-lg bg-neutral text-neutral-content rounded-box">
            <div className="px-2 mx-2">
              <span className="text-lg font-bold">
                      Document Management
              </span>
            </div>
           
                        <div className="">
              <button className="btn btn-square btn-ghost">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" className="inline-block w-6 h-6 stroke-current">           
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>               
                </svg>
              </button>
            </div>
          </div>
        </div>
    )
}

export default Header;
